blank_issues_enabled: true
contact_links:
  - name: Ask Pyrogram related questions
    url: https://stackoverflow.com/questions/tagged/pyrogram
    about: This place is only for reporting issues about Pyrogram. You can ask questions on StackOverflow.
  - name: Join the Telegram channel
    url: https://t.me/PyroTGFork
    about: Join the official channel and stay tuned for news, updates and announcements.
